max_concurrency = 16
max_retries = 1
timeout = 10

exclude = [
  "https?://(www\\.)?dayi\\.com/.*",
  "https?://(www\\.)?guiji\\.ai/.*",
  "https?://(www\\.)?jusda\\.com/.*",
  "https?://(www\\.)?minimax\\.chat/.*",
  "https?://(www\\.)?mofudata\\.com/.*",
  "https?://(www\\.)?prospera\\.ag/.*",
  "https?://(www\\.)?speechocean\\.com/.*",
  "https?://(www\\.)?csm\\.ai/.*",
  "https?://(www\\.)?play\\.ht/.*",
  "https?://docs\\.midjourney\\.com/.*",
  "https?://chat\\.openai\\.com/.*",
  "https?://(www\\.)?claude\\.ai/.*",
  "https?://(www\\.)?gamma\\.app/.*",
  "https?://genie\\.tmall\\.com/.*",
  "https?://(www\\.)?humanly\\.io/.*",
  "https?://(www\\.)?ideogram\\.ai/.*",
  "https?://(www\\.)?leonardo\\.ai/.*",
  "https?://(www\\.)?looka\\.com/.*",
  "https?://(www\\.)?nightcafe\\.studio/.*",
  "https?://(www\\.)?openai\\.com/index/dall-e-3/.*",
  "https?://(www\\.)?pi\\.ai/.*",
  "https?://(www\\.)?pitch\\.com/.*",
  "https?://(www\\.)?platform\\.openai\\.com/.*",
  "https?://(www\\.)?poe\\.com/.*",
  "https?://(www\\.)?scite\\.ai/.*",
  "https?://(www\\.)?sora\\.com/.*",
  "https?://(www\\.)?superclue\\.ai/.*",
  "https?://(www\\.)?typeset\\.io/.*",
  "https?://(www\\.)?ada\\.cx/.*",
  "https?://(www\\.)?adobe\\.com/products/photoshop-lightroom\\.html.*",
  "https?://(www\\.)?adobe\\.com/products/photoshop\\.html.*",
  "https?://(www\\.)?autodesk\\.com/products/forma/.*",
  "https?://(www\\.)?canva\\.com/.*",
  "https?://(www\\.)?cognex\\.com/.*",
  "https?://(www\\.)?craiyon\\.com/.*",
  "https?://(www\\.)?hilton\\.com/.*",
  "https?://(www\\.)?hopper\\.com/.*",
  "https?://(www\\.)?mailbutler\\.io/.*",
  "https?://(www\\.)?newrank\\.cn/.*",
  "https?://(www\\.)?perplexity\\.ai/.*",
  "https?://(www\\.)?phind\\.com/.*",
  "https?://(www\\.)?stableaudio\\.com/.*",
  "https?://(www\\.)?tesla\\.com/autopilot.*",
  "https?://(www\\.)?unrealengine\\.com/.*",
  "https?://(www\\.)?azure\\.microsoft\\.com/en-us/products/ai-services/ai-document-intelligence/.*",
  "https?://(www\\.)?longmaodata\\.com/.*",
  "https?://(www\\.)?make\\.com/.*"
]
